testing_mode = false
stripe_api_key = "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"
stripe_link = "https://buy.stripe.com/cNi7sM4Hh58FgHueRUg7e02"


stripe_api_key_test = "sk_test_..."
stripe_link_test = "https://buy.stripe.com/test_..."
